---
extends:
  - standard
  - plugin:node/recommended
plugins:
  - no-only-tests
rules:
  node/exports-style: ["error", "module.exports"]
  semi: ["warn", "always"]
  no-only-tests/no-only-tests: error
  quotes: ["warn", "double"]
